### ISSUE TITLE
Database search failure

### ISSUE THREAD

**Issue by LUNARY273** [metabolomics-us/mona#86]
![Database search failure](https://user-images.githubusercontent.com/129154425/230698234-259625c5-1d0d-4e50-9657-64e9fad85ee3.png)

**Comment by NolanGuzman97** [comment]
@LUNARY273  Hi there, can you provide the query that failed for you? If you click the "Display Generated Query" button that will provide me the query so I can look into your issue further. Thanks!

**Comment by NolanGuzman97** [comment]
Will close out this ticket if no response by end of Friday and assume the issue has not persisted.

**Comment by Celine-Fr** [comment]
Hello,

I have the same problem for all links that I try to open from pubchem... I put an example beneath:
https://mona.fiehnlab.ucdavis.edu/spectra/browse?query=compound.metaData%3Dq%3D%27name%3D%3D%22InChIKey%22%20and%20value%3D%3D%22GJZJZRWFRZFTEE-ARJAWSKDSA-N%22%27 
This link is supposed to match with "2-[2-[(Z)-pent-2-enyl]-3-[3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxycyclopentyl]acetic acid"
Is it due to mona update or something else?

Have a good day

**Comment by NolanGuzman97** [comment]
Hi @Celine-Fr, yes this issue is due to the new MoNA update. We have a new query style and that link you have uses the old query style so it will not work. You can see how to use the new query style at this link https://mona.fiehnlab.ucdavis.edu/documentation/query .  And to save you some time, here is how that same link should look after using the new query style https://mona.fiehnlab.ucdavis.edu/spectra/browse?query=exists(compound.metaData.name:%27InChIKey%27%20and%20compound.metaData.value:%27GJZJZRWFRZFTEE-ARJAWSKDSA-N%27) . Make sure to click on "Display Generated Query" to see the new query format. Hope this helps!

**Comment by Celine-Fr** [comment]
After having a look at your links I succeeded to find other molecules, thank you really much Nolan!

De : Nolan Guzman ***@***.***>
Envoyé : lundi 17 avril 2023 17:04
À : metabolomics-us/mona ***@***.***>
Cc : Celine Brosse ***@***.***>; Mention ***@***.***>
Objet : Re: [metabolomics-us/mona] Database search failure (Issue #86)


Hi @Celine-Fr<https://github.com/Celine-Fr>, yes this issue is due to the new MoNA update. We have a new query style and that link you have uses the old query style so it will not work. You can see how to use the new query style at this link https://mona.fiehnlab.ucdavis.edu/documentation/query . And to save you some time, here is how that same link should look after using the new query style https://mona.fiehnlab.ucdavis.edu/spectra/browse?query=exists(compound.metaData.name:%27InChIKey%27%20and%20compound.metaData.value:%27GJZJZRWFRZFTEE-ARJAWSKDSA-N%27) . Make sure to click on "Display Generated Query" to see the new query format. Hope this helps!

**Comment by NolanGuzman97** [comment]
@Celine-Fr great to hear!

**Comment by LUNARY273** [comment]
I'm sorry that I couldn't check the email for a long time due to network problems. Fortunately, I found a solution from your email exchange with Celine-Fr, which is very helpful, thank you very much!
